def init_state():
    return {
        "functions": {},
        "last_loaded_image": None,
        "last_loaded_image_name": None,
        "last": None,
        "last_function_type": None,
        "last_function_args": None,
        "image_stack": [],
        "detections_stack": [],
        "poses_stack": [],
        "history": [],
        "search_index_stack": [],
        # "current_active_model": None,
        "output": None,
        "input_variables": {},
        "last_classes": [],
        "confidence": 50,
        "active_region": None,
        "active_filters": {"class": None, "region": None},
        "load_queue": [],
        "stack_size": {"image_stack": 0},
        "show_text_count": 0,
        "in_concurrent_context": False,
        "ctx": {},
        "tracker": None,
        "run_video_in_background": False
    }
